SejongPeer/SejongPeerFront

src/Components/Buddy/BuddyStart/BuddyStart.module.css
src/Components/Buddy/BuddyStart/BuddyStart2.js
src/Components/Buddy/BuddyStart/BuddyStart3.js

버디 매칭 페이지 시작 부분 start2까지만하고, 글귀 수정했습니다

feat: 버디 매칭페이지 수정

---

.github/workflows/deploy.yml

deploy branch 변경 및 cloudFront 주석 해제

deploy branch 변경 및 cloudFront 주석 해제

---

src/Components/Login/SignUp/IDCheckBox.js
src/Components/Login/SignUp/InputTextBox.js
src/Components/Login/SignUp/NickNameBox.js

아이디, 닉네임 validate 수정으로
정규식 표현에 대한 수정과 검증 Boolean 변수를 return 받는 함수로 수정

아이디, 닉네임 validate 수정

---

.github/workflows/deploy.yml

GA, GENERATE_SOURCEMAP env 환경 변수 추가

GA, GENERATE_SOURCEMAP 변수 추가

---

src/Components/Login/Find/ResetPwd.js

inputPwd 수정

---

src/pages/study/studyModify/studyModify.js
src/pages/study/studyPostDetail/StudyPostDetail.js
src/pages/study/studyPostDetail/api.js
src/pages/study/studyPostDetail/useStore.js
src/pages/study/studyPostWrite/StudyPostWrite.js

- 스크랩 추가, 삭제 기능 구현
- localstorage를 이용하여 scrapId를 저장
- (ex) scrapId_${studyId} 기존의 studyId를 이용하여 api 호출 후 response에 담긴 scrapId를 저장
- console에서 찍히는 scrapId는 data라고 명시되어있음 (헷갈리면 안됨!)
- 추가, 삭제 시 alert 뜨게 함
- #341 
- 스크린샷은 따로 없음
- console.log로 테스트 한 부분 다 주석처리함 (내 부분만 ex) StudyPostDetail.js, api.js 등)

feat: [10] 스크랩 추가, 삭제 기능 구현

---

src/components/studyPostWrite/studyRequirement/MeetingWay.js
src/pages/main/mainPage/MainPage.js
src/pages/study/studyPostWrite/StudyPostWrite.js
src/pages/study/studyPostWrite/usePostStore.js
src/pages/study/useStudyInfoStore.js

- 게시글 작성 통신(교내)
- 카테고리 및 이미지는 아직 미완성
- #343 
-
-

feat : [11] 게시글 작성 통신 (교내)

---

src/pages/study/studyPostDetail/StudyPostDetail.js
src/pages/study/studyPostDetail/api.js

- 단건 게시물 (StudyPostDetail.js)에 접속 시 게시물 별 스크랩 수 조회하는 api 구현
- api.js에 함수 작성 -> return response.data, StudyPostDetail.js에서 { scrapCount }로 받아옴
- #345

feat: [12] 단건 게시물 별 스크랩 수 조회 구현

---

src/pages/study/studyPostDetail/StudyPostDetail.js

- 단건 게시물 조회 시 모임 방식, 빈도, 문의 링크(카카오 오픈채팅방 링크) 구현
- #347

feat: [13] 단건 게시물 조회 시 모임 방식, 빈도, 문의 링크 구현

---

src/pages/study/studyList/api.js
src/pages/study/studyPostWrite/StudyPostWrite.js
src/pages/study/studyPostWrite/usePostStore.js

-이미지 업로드 통신 추가
- 교내 || 교외 통신 Url 부분 studyType으로 구별
- 추후에 함수 따로 분리 필요
- 카테고리 미완
- 유효성 검사 필요
- #350 
-
-

feat : [15] 이미지 업로드 & 교내 || 교외 통신 시 URl studyType설정

---

src/components/studyPostWrite/studyRequirement/Tag.js
src/pages/study/studyModify/studyModify.js
src/pages/study/studyPostWrite/StudyPostWrite.js

- 스터디 정보 불러오기
- 스터디 수정 정보 통신
- 이미지 렌더링은 아직입니다.
-
-

feat: [19] 스터디 수정

---

src/pages/myPage/mypage/MyPage.js
src/pages/myPage/mypage/MyPage.module.css

css : 마이페이지 수정된 css 1차

---

src/App.js
src/pages/myPage/mypage/MyPage.js
src/pages/myPage/mypage/MyPageScrapList.js
src/pages/myPage/mypage/api.js
src/pages/myPage/mypage/useScrapStore.js

feat : [21] mypage좋아요 한 글 목록 불러오기 통신 + css

---

src/pages/main/mainPage/MainPage.js
src/pages/main/mainPage/MainPage.module.css
src/pages/main/mainPage/api.js
src/pages/myPage/mypage/api.js
src/pages/study/studyList/StudyListPost.js
src/pages/study/studyList/api.js
src/pages/study/studyPostDetail/api.js

- 메인 페이지 데탑 버전 디자인 수정
- api.js 분리
- #369 
-

fix: [23] 메인 페이지 데탑 디자인 수정 및 api 분리

---

src/App.js
src/components/studyMyPost/api.js
src/components/studyMyPost/studyMyPost.js
src/components/studyMyPost/studyMyPost.module.css
src/pages/myPage/myPost/myPost.js
src/pages/myPage/myPost/myPost.module.css
src/pages/study/studyPostWrite/studyPostField/StudyPostField.module.css

- 게시글 작성 카테고리 css수정
- 내스터디 게시글 관리 css 모바일
- #377 
- 게시글 작성 
-

feat : [27] 게시글 작성 카테고리 css수정 & 내스터디 게시글 관리 css 모바일

---

src/App.js
src/components/studyMyPost/api/applicantSelection.js
src/components/studyMyPost/api/earlyClose.js
src/components/studyMyPost/api/fetchMyPost.js
src/components/studyMyPost/studyMyPost.js
src/pages/myPage/myPost/myPost.js
src/pages/study/studyPostWrite/StudyPostWrite.js

-게시글 작성 alert 및 이동
-수락/거절 통신 
- 모집 마감 통신 좀 더 봐야 함
- 모집 마감 여부/ 지원자 수락 여부 데이터 필요
- #379 
-

feat : [28] 게시글 작성 -> alert & 작성한 스터디 지원자 조회 css & 수락 거절 통신

---

src/components/modal/BottomModal.js
src/components/studyPostWrite/StudyRequirement.module.css
src/components/studyPostWrite/studyRequirement/DateFrequency.js
src/components/studyPostWrite/studyRequirement/MeetingWay.js
src/pages/myPage/mypage/MyPage.js
src/pages/study/studyPostDetail/StudyPostDetail.js
src/pages/study/studyPostDetail/api.js
src/pages/study/studyPostWrite/ConfirmModal.js
src/pages/study/studyPostWrite/ConfirmModal.module.css
src/pages/study/studyPostWrite/StudyPostWrite.js
src/pages/study/studyPostWrite/confirmModal/ConfirmModal.js
src/pages/study/studyPostWrite/confirmModal/ConfirmModal.module.css

feat: 게시글 사진 렌더링 등

---

jsconfig.json
package-lock.json
package.json
src/App.js
src/pages/login/signIn/SignIn.js
src/pages/login/signUp/SignUp.js
src/pages/login/signUp/auth/Auth.js
src/pages/main/mainPage/MainPage.js
src/pages/main/mainPage/api.js
src/pages/myPage/modify/Modify.js
src/pages/myPage/mypage/AppliedStudy.js
src/pages/myPage/mypage/MyPage.js
src/pages/myPage/mypage/MyPage.module.css
src/pages/myPage/mypage/api.js
src/pages/study/studyList/StudyListPost.js
src/pages/study/studyList/api.js
src/pages/study/studyPostDetail/StudyPostDetail.js
src/pages/study/studyPostDetail/api.js

- 내가 지원한 스터디 조회 구현 완료
- 디자인 추후 변경 예정 (서버에서 좋아요 수 반환 추가 시)
- 스크랩 수 스터디 전체 조회 시 보이게 구현
- alert 대신 toast 메세지 추가
- #383 #353 
- `useSearchParams` 을 통한 `refactor` 진행 예정

feat: [30] 내가 지원한 스터디 조회

---

debug.log
src/components/studyMyPost/api/debug.log
src/components/studyMyPost/api/earlyClose.js
src/components/studyMyPost/debug.log
src/components/studyMyPost/studyMyPost.js
src/components/studyPopup/debug.log
src/pages/myPage/myPost/debug.log
src/pages/study/studyPostWrite/debug.log

- 내가 쓴 스터디  게시글 수락/거절 통신
- 내가 쓴 스터디 게시글 모집 마감 통신
- #387 
-
-

feat : [32] 내가 쓴 게시글 수락/거절 통신 & 모집 마감 통신

---

src/pages/myPage/mypage/AppliedStudy.js
src/pages/study/studyPostDetail/StudyPostDetail.js

- 마이페이지에 있는 내가 지원한 스터디의 리스트 디자인 수정
- 스크랩 수 반영
- NaN 버그 수정
- #397

feat: [37] 지원한 스터디 디자인 수정

---

src/pages/study/studyPostWrite/StudyPostWrite.js
src/pages/study/studyPostWrite/studyPostField/StudyPostField.js
src/pages/study/studyPostWrite/studyPostField/StudyPostField.module.css
src/pages/study/timeTable/getTimeTable.js
src/pages/study/timeTable/useTimeTableStore.js

- 카테고리 뒤로 가기 기능 구현 
- tags 없이 게시글 작성할 경우 생기는 오류 수정
- #403 
- 
-

[40] 카테고리 뒤로 가기 기능 구현 , tags 없이 게시글 작성할 경우 생기는 오류 수정

---

public/index.html
src/components/modal/Modal.js
src/components/modal/Modal.module.css
src/components/studyPostWrite/ImageUpload.js
src/pages/myPage/mypage/MyPage.js
src/pages/myPage/mypage/api.js
src/pages/study/studyList/Filter_Field.js
src/pages/study/studyList/Filter_Field.module.css
src/pages/study/studyList/Filter_Field2.js
src/pages/study/studyList/Filter_Member.js
src/pages/study/studyList/StudyList.js
src/pages/study/studyList/api.js
src/pages/study/studyList/useFilterStore.js
src/pages/study/studyList/useTimetableStore.js
src/pages/study/studyPostDetail/StudyPostDetail.js
src/pages/study/studyPostWrite/StudyPostWrite.js

- 이미지 용량 클 시, 에러처리 및 업로드 금지
- 이미지 확대 보기 모달 생성
- 필터 통신 작업중 (에러발생되는거 맞)
-

feat: 이미지 확대 보기, 이미지 용량 에러처리, 통신 작업중

---

src/components/headerRefactor/SubHeader.js
src/components/modal/BottomModal.module.css
src/components/studyMyPost/navBar.js
src/components/studyMyPost/studyMyPost.js
src/components/studyPostWrite/studyRequirement/StudyLink.js
src/pages/study/studyPostWrite/StudyPostWrite.js
src/pages/study/studyPostWrite/StudyPostWrite.module.css
src/pages/study/studyPostWrite/studyPostField/StudyPostExternalField.js
src/pages/study/studyPostWrite/studyPostField/StudyPostField.js
src/pages/study/studyPostWrite/studyPostField/StudyPostField.module.css
src/pages/study/timeTable/useTimeTableStore.js

-검색창 placeholder 수정
- 게시글 작성:"신청 수락시"->"모집 마감시"로 수정
- 간격 css 수정
- 수락/거절 클릭 이후 바로 글씨 바꾸기
- #413 
-
-

feat : [45] 검색창 placeholder수정 , 수락/거절 이후 바로 바뀌게

---

src/pages/study/studyPostDetail/StudyPostDetail.js

- [x] 리팩토링 (개선 느낌) (refactor)
- 스터디 지원 시 1번 게시글을 지원 후 2번 게시글로 이동 시 지원하지 않았는데도 `지원 취소`로 변경되어있음
- #418 
-
-

refactor: [52] 스터디 지원 버그 수정

---

public/index.html
src/pages/study/studyPostDetail/StudyPostDetail.js

feat: [50] Google Analytics 설정

---

src/pages/study/studyPostDetail/StudyPostDetail.js

Build 오류 수정

---

src/components/studyMyPost/studyMyPost.js
src/pages/study/studyList/Filter_Field.js
src/pages/study/studyPostWrite/StudyPostWrite.js
src/pages/study/studyPostWrite/studyPostField/StudyPostField.js

-수락/거절 오류
- 인원수 잘못뜨는 오류 해결
- 검색 필터링 기능(게시글 작성시에만)
- 내가 쓴 게시글 지원자 리스트 예외 처리
- 지원 취소한 경우
- 모집 인원수 마감된 후 수락/거절 하는 경우
- #415 
-
-

feat : [46] 거절 안됨 오류 / 인원수 잘못뜨는 오류 / 검색 필터링 기능 / 내가 쓴 게시글 지원자 리스트 예외처리 

---

jsconfig.json
src/components/headerRefactor/SubHeader.js
src/pages/buddy/accept/BuddyAccept.js
src/pages/buddy/info/BuddyStart.module.css
src/pages/buddy/info/BuddyStart2.js
src/pages/buddy/matching/css/B_Container.module.css
src/pages/buddy/waiting/BuddyWaiting.js
src/pages/honbob/matching/js/H_Menu.js
src/pages/honbob/success/HonbobSuccess.js
src/pages/honbob/waiting/HonbobWaiting.js
src/pages/study/studyPostDetail/StudyPostDetail.js
src/pages/study/studyPostDetail/api.js

- QA 1차 반영
- 혼밥탈출 return
- `SubHeader` 누락 부분 추가
- 절대 경로 수정
- 지원 여부 서버 통신 완료 (isApplied)
- #421 
-
-

refactor: [49] QA 1차 반영

---

src/App.js
src/components/headerRefactor/SubHeader.js
src/pages/buddy/accept/BuddyAccept.js
src/pages/buddy/info/BuddyStart1.js
src/pages/buddy/info/BuddyStart2.js
src/pages/buddy/matching/js/Buddy_Matching.js
src/pages/buddy/success/BuddySuccess.js
src/pages/buddy/success/BuddySuccess.module.css
src/pages/buddy/waiting/BuddyWaiting.js
src/pages/honbob/info/HonbobStart1.js
src/pages/honbob/matching/js/Honbob_Matching.js
src/pages/honbob/success/HonbobSuccess.js
src/pages/honbob/success/HonbobSuccess.module.css
src/pages/honbob/waiting/HonbobWaiting.js
src/pages/login/find/findId/FindId.js
src/pages/login/find/resetPwd/ResetPwd.js
src/pages/login/signIn/SignIn.js
src/pages/login/signUp/Agree.js
src/pages/login/signUp/SignUp.js
src/pages/login/signUp/auth/Auth.js
src/pages/myPage/modify/Modify.js
src/pages/myPage/myPost/myPost.js
src/pages/myPage/mypage/AppliedStudy.js
src/pages/myPage/mypage/MyPage.js
src/pages/myPage/mypage/MyPageScrapList.js
src/pages/study/studyList/StudyList.js
src/pages/study/studyPostDetail/StudyPostDetail.js
src/pages/study/studyPostWrite/StudyPostWrite.js

feat: [56] 커스텀 경로 설정

---

src/components/headerRefactor/SubHeader.js

SubHeader 수정

---

src/pages/study/studyList/StudyListPost.js
src/pages/study/studyPostDetail/StudyPostDetail.js
src/pages/study/studyPostWrite/StudyPostWrite.js

- 게시글 수정 안되는 버그  해결
- 스터디 리스트에 발생하는 DOM props 에러 해결
-
-

feat: 스터디 수정 및 에러 해결

---

src/components/studyMyPost/studyMyPost.js

- 모집마감 버튼 외 다른 부분 클릭해도 마감되는 오류 수정
- 수락 버튼 클릭시 인원 채워지면 모집 마감 
- #439 
-
-

feat : [57] 모집 마감 버튼 클릭 범위 수정 & 수락 버튼 클릭시 인원 찬 경우 모집 마감

---

src/pages/myPage/myPost/myPost.js
src/pages/myPage/mypage/AppliedStudy.js

내가 지원한 스터디에서 스크랩 수정

---

src/pages/study/studyPostWrite/StudyPostWrite.js

feat: 이미지 용량 처리

---

src/pages/main/mainPage/api.js
src/pages/myPage/mypage/MyPage.js
src/pages/study/studyList/StudyList.js

feat: 버디/혼밥 임시 fix

---

src/pages/login/find/findId/FindId.js
src/pages/main/mainPage/api.js

fix: 아이디 찾기 오류 해결

---

src/pages/honbob/waiting/HonbobWaiting.js

fix: 혼밥 멘트 수정

---

src/pages/login/signUp/InputTextBox.js
src/pages/myPage/mypage/AppliedStudy.js

feat: 비밀번호 유효성 추가

---

src/pages/login/signUp/EmailBox.js
src/pages/login/signUp/InputTextBox.js
src/pages/login/signUp/SignUpElement.js
src/pages/login/signUp/SignUpElement.module.css

fix: 회원가입 에러메시지 수정

---

src/pages/myPage/mypage/MyPage.js

feat: 마이페이지-세종스터디 이용방법 링크 추가

---

src/pages/study/studyPostDetail/StudyPostDetail.js

fix: 게시글 줄 바꿈 추가

---

public/index.html

google analytics 수정

---

src/pages/buddy/info/BuddyStart2.js
src/pages/honbob/info/HonbobStart1.js
src/pages/main/mainPage/api.js

버디, 혼밥 로그인 수정
